<?php

namespace App\Enum;

class NotificationEnum
{
	// notification send by
	const NOTIFICATION_SEND_BY_ADMIN = 0;
	// notification type
	const ADMIN_USER_ACTION_NOTIFICATION = 1;
	const WALLET_MONEY_ADDED = 2;
	const BOOKING_NOTIFICATION = 3;
	const REFERRAL_USER_NOTIFICATION = 4;
	const BOOKING_ACCEPTED_NOTIFICATION = 5;
	const BOOKING_REJECTED_NOTIFICATION = 6;
	const VENDOR_OUT_FOR_SERVICE = 7;
	const VENDOR_STARTED_SERVICE_JOB = 8;
	const VENDOR_JOB_FINISHED = 9;
	const BOOKING_CANCELLED = 10;
	const VENDOR_LOCATION_CHANGED = 11;
	const VENDOR_REACHED_LOCATION = 12;
	const BOOKING_RESCHEDULE_NOTIFICATION = 13;
	const PAYMENT_TRANSFER_SUCCESS = 14;
	// const PAYMENT_TRANSFER_NOTIFICATION
}
